version: '3.1'
services:
  app:
    image: ruby:2.7.1
    env_file:
      - .env
    ports:
      - "9292:9292"
    working_dir: /app
    volumes:
      - ./Gemfile:/app/Gemfile
      - ./Gemfile.lock:/app/Gemfile.lock
      - ./config.ru:/app/config.ru
      - ./vendor/bundle:/usr/local/bundle
    command: bash -c "bundle install && bundle exec rackup -o 0.0.0.0"
